apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sas-local
provisioner: ebs.csi.aws.com
parameters:
  fsType: ext4
  type: gp3
  encrypted: "true"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
